name: echoai
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_ai: ^3.5.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.3
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  speech_to_text: ^7.3.0
  sqflite: ^2.4.2
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1

flutter:
  uses-material-design: true
